### ISSUE TITLE
NOW THIS IS WHAT IM TALKIN ABOUT

### ISSUE THREAD

**Issue by mikey-** [pwillis-els/terraformsh#1]
love it, thank you

**Comment by antonbabenko** [comment]
Good work @pwillis-els !

It reminds me of saying that `Every Developer Should Write Their Own Framework`. I am personally very glad to see projects where established practices and popular tools are being questioned.

**Comment by mikey-** [comment]
> I am personally very glad to see projects where established practices and popular tools are being questioned.

_- @antonbabenko_
 
 Absolutely, me too.
