### ISSUE TITLE
terraform validate command error

### ISSUE THREAD

**Issue by AMKamel** [pwillis-els/terraformsh#10]
Hello @pwillis-els ,

I think it's a syntax error to use `terraform validate` command with `-var-file` option as it produced syntax errors with me. it only seem to support two options as in screenshot, right?
```
╷
│ Error: Failed to parse command-line flags
│ 
│ flag provided but not defined: -var-file
╵
```
![image](https://user-images.githubusercontent.com/14953512/141243109-1adbcacb-57ce-4df3-abd5-7a934fa41afb.png)

**Comment by pwillis-els** [comment]
Yep!

I merged some code recently (https://github.com/pwillis-els/terraformsh/pull/7) (https://github.com/pwillis-els/terraformsh/pull/8) which *should* prevent passing those args to validate unless it's a version of Terraform earlier than 0.12, when those args used to be accepted.

Which version of terraformsh are you running, and which version of terraform? (I haven't made a new release of terraformsh with the changes yet, so you'll have to get the latest copy here: https://raw.githubusercontent.com/pwillis-els/terraformsh/main/terraformsh)

**Comment by AMKamel** [comment]
At the time was using 0.10 and terraform 1.0.10

**Comment by AMKamel** [comment]
It looks resolved by latest update but I got another problem which is that it seems `terraformsh` don't use workspaces and there is no way I found applicable to do the execution against some workspace

See in screenshot how it has ignore that we are in different workspace and tried to alter the current state of default workspace instead of use the current space?
![image](https://user-images.githubusercontent.com/14953512/141280465-fcc64f2b-2851-48aa-ab33-c57d32f677bd.png)

**Comment by pwillis-els** [comment]
That's interesting, I haven't used workspaces with the tool so I'm not sure what's going on. I'll need to do some testing.

I've created a new issue to track your workspaces issue: https://github.com/pwillis-els/terraformsh/issues/11

I have a suggestion there for something to try in the mean time
