### ISSUE TITLE
Some sed commands does not behave correctly on MacOS

### ISSUE THREAD

**Issue by Th0masL** [pwillis-els/terraformsh#14]
I've been running into some problems, and after investigating the problem is related to the fact that the `sed` binary does not behave the same way on MacOS than on Linux.

Here is an overview, when trying to detect the Backend bucket name for `aws_bootstrap` function on my Mac laptop:

```
# Using sed (MacOS version):
$ grep -e "^[[:space:]]*bucket[[:space:]]\+=" < backend.sh.tfvars | sed -e 's/^[[:space:]]*bucket[[:space:]]\+=[[:space:]]*//; s/^"//g; s/"$//g'
    bucket         = "terraform-state-bucket-test-20220723
    
# Using gsed (GNU sed):
$ grep -e "^[[:space:]]*bucket[[:space:]]\+=" < backend.sh.tfvars | gsed -e 's/^[[:space:]]*bucket[[:space:]]\+=[[:space:]]*//; s/^"//g; s/"$//g'
terraform-state-bucket-test-20220723
```

We have two ways to approach the problem:
- either we detect the name of the type of the operating system at the start of the script and if this is a MacOS, use `gsed` and throw an error if not installed
- or we try to change the `sed` commands to make it compatible with both the GNU and the MacOS version

I can work on a PR for that 🙂

**Comment by Th0masL** [comment]
Ok so the problem seems to be that the MacOS version of `sed` only support the `+` regexp when using `sed -E` (for Extended Regular Expression support) :

So switching to `sed -E` is fixing the problem, but we also need to remove the escaping `\` on `\+`.

**Comment by pwillis-els** [comment]
Thanks for the PR! Fix looks good to me, I've approved and merged it

**Comment by Th0masL** [comment]
Thanks !
